name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-python-app .

    # Run Docker container to make sure everything works
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 my-python-app
        curl http://localhost:5000

    # Push Docker image to Docker Hub (Optional)
    - name: Push Docker image to Docker Hub
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag my-python-app $DOCKER_USERNAME/my-python-app
        docker push $DOCKER_USERNAME/my-python-app
